os: 
 - windows
 - linux
 - osx
language: node_js
env:
  - YARN_GPG=no
node_js:
- '12.17.0'
cache:
  yarn: true
script: node -v
before_deploy:
  - yarn global add electron-builder
  - cd app
  - VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
  - yarn install --no-lockfile --prod
  - yarn construct:store
  - if [ "$TRAVIS_OS_NAME" = "osx" ];then electron-builder --mac -p never;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];then cd ../build;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];then mv *.dmg TheDesk-$VERSION-store.dmg;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];then cd ../app;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];then electron-builder --linux snap:x64 -p never;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];then cd ../build;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];then mv *.snap TheDesk-$VERSION-store.snap;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];then cd ../app;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then yarn add electron-builder;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then electron-builder --win appx:x64 -p never ;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then cd ../build;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then mv *.appx TheDesk-$VERSION-store.appx;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then cd ../app;else :;fi
  - yarn construct
  - if [ "$TRAVIS_OS_NAME" = "osx" ];then electron-builder --mac -p never;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];then electron-builder --linux --x64 -p never;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];then cd ../build;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];then ls;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];then mv thedesk-*.zip thedesk.zip;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];then cd ../app;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then electron-builder --win --ia32 -p never;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then cd ../build;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then ls;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then mv TheDesk-setup.exe TheDesk-setup-ia32.exe;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then mv *$VERSION.exe TheDesk-ia32.exe;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then cd ../app;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then electron-builder --win --x64 -p never;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then cd ../build;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then ls;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then mv ../build/TheDesk-setup.exe ../build/TheDesk-setup.exe;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then mv ../build/*$VERSION.exe ../build/TheDesk.exe;else :;fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then cd ../app;else :;fi
  - cd ../
  - ls build
deploy:
  provider: releases
  # GitHub にリリースするための API KEY を暗号化した値
  api_key:
    secure: jndR02p5KRTtcJk18b3YsXL2cC+yzEf1AOqXdpWciF8f3lO5oY01jlxd17xdHIcK7VywSsLVZpLToSdqAoIEhJ5OxEQ/FmA3FlmbwwD6ou13gLa4VGIvsBHveCmKGjVu0Z++atIy76tZYU1SOWFWv4B0ZhnVz2ca2VZynvLgw3YNsPJH7rHO966GXgRkGYJAJ4UvLg3sj/iztVh2FSfbUj5IGO1e/JHJO63wAo1MSQtRjkutVgl/djnBLC6vbL4YHkM3Ynpkx/YQEcxwrmeY0Ra8D5yYDq4MNIDMmZahWC+k4u2eA2Cj2ifBFNxbZvTN75vLwRBp6DsTNHsiqkXrSPDBdNeet31RbwTQ6LtsK8jqmL4S/59dmLcj7uCU2WxyBLPbJdbdZWlqW2ZQvfQY8QVAYy7S3MiHQWQN0oP5wqXk89jcgR42ig/zsqFNPpXHM4mExR7l/gDLPg0j9c3XEF6sWtk3FmJN1i4+B+9kn09b6UKlV7EFPKp8XcFNrz4ZcE9/I8lKwsqLVG2jAXIk7Z9LwDRcAmK5eG348X5zwFtOY6raKIvRw2cn92bPnEI+55v8A4WANS2647GFTgxHj30D0d/sOZmJ5BS34zpdWTgE0AlKg7sOqkncjqoW5J5zCh5Ow7b3KXvEvlAts44mAag8tZTectxMP4iguXvTnv4=
  # Releases ページにアップロードするファイル
  file_glob: true
  file:
    - build/*
  skip_cleanup: true
  on:
    repo: cutls/TheDesk
    tags: true
branches:
  only: "/^v?[0-9\\.]+/"
